apiVersion: apps/v1
kind: Deployment
metadata:
  name: sboot-backend-k8s
  namespace: default
  labels:
    app: sboot-backend-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sboot-backend-k8s
  template:
    metadata:
      labels:
        app: sboot-backend-k8s
    spec:
      containers:
      - name: sboot-backend-k8s
        image: sboot-backend
        args: []
        ports:
        - containerPort: 8080
        resources: {}