package com.jvp.poc.domain.core;
// Generated 17/03/2019 10:38:14 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import org.hibernate.annotations.Where;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
@Where(clause="apellido like '%'")
public class Persona implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -2303698009909125908L;
	@Id
	@GeneratedValue(generator = "personaSeq", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(sequenceName = "persona_seq", name = "personaSeq", schema = "public", allocationSize = 1)
	@Column(name = "persona_id", unique = true, nullable = false)
	private BigDecimal personaId;
	@Column(name = "apellido", length = 150)
	private String apellido;
	@Column(name = "nombre", length = 150)
	private String nombre;
	@Column(name = "direccion", length = 150)
	private String direccion;

	public Persona() {
		// TODO Auto-generated constructor stub
	}

	public BigDecimal getPersonaId() {
		return personaId;
	}

	public void setPersonaId(BigDecimal personaId) {
		this.personaId = personaId;
	}

	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
